"""
    Criteo API

    Criteo API - RetailMedia  # noqa: E501

    The version of the OpenAPI document: Preview
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from criteo_api_retailmedia_preview.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from criteo_api_retailmedia_preview.exceptions import ApiAttributeError


def lazy_import():
    from criteo_api_retailmedia_preview.model.bidding_request import BiddingRequest
    from criteo_api_retailmedia_preview.model.line_item_capping_target_request import LineItemCappingTargetRequest
    from criteo_api_retailmedia_preview.model.line_item_pacing_request import LineItemPacingRequest
    from criteo_api_retailmedia_preview.model.targets_request import TargetsRequest
    globals()['BiddingRequest'] = BiddingRequest
    globals()['LineItemCappingTargetRequest'] = LineItemCappingTargetRequest
    globals()['LineItemPacingRequest'] = LineItemPacingRequest
    globals()['TargetsRequest'] = TargetsRequest


class AuctionDisplayLineItemCreateModel(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('media_type',): {
            'DISPLAY': "display",
            'VIDEO': "video",
        },
        ('page_types',): {
            'SEARCH': "search",
            'HOME': "home",
            'CHECKOUT': "checkout",
            'CATEGORY': "category",
            'PRODUCTDETAIL': "productDetail",
            'CONFIRMATION': "confirmation",
            'MERCHANDISING': "merchandising",
            'DEALS': "deals",
            'FAVORITES': "favorites",
            'SEARCHBAR': "searchBar",
            'CATEGORYMENU': "categoryMenu",
        },
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'bidding': (BiddingRequest,),  # noqa: E501
            'budget': (float,),  # noqa: E501
            'creative_ids': ([str],),  # noqa: E501
            'is_active': (bool,),  # noqa: E501
            'media_type': (str,),  # noqa: E501
            'name': (str,),  # noqa: E501
            'pacing': (LineItemPacingRequest,),  # noqa: E501
            'page_types': ([str],),  # noqa: E501
            'product_ids': ([str],),  # noqa: E501
            'retailer_id': (str,),  # noqa: E501
            'start_date': (datetime,),  # noqa: E501
            'end_date': (datetime, none_type,),  # noqa: E501
            'frequency_capping': (LineItemCappingTargetRequest,),  # noqa: E501
            'targets': (TargetsRequest,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'bidding': 'bidding',  # noqa: E501
        'budget': 'budget',  # noqa: E501
        'creative_ids': 'creativeIds',  # noqa: E501
        'is_active': 'isActive',  # noqa: E501
        'media_type': 'mediaType',  # noqa: E501
        'name': 'name',  # noqa: E501
        'pacing': 'pacing',  # noqa: E501
        'page_types': 'pageTypes',  # noqa: E501
        'product_ids': 'productIds',  # noqa: E501
        'retailer_id': 'retailerId',  # noqa: E501
        'start_date': 'startDate',  # noqa: E501
        'end_date': 'endDate',  # noqa: E501
        'frequency_capping': 'frequencyCapping',  # noqa: E501
        'targets': 'targets',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, bidding, budget, creative_ids, is_active, media_type, name, pacing, page_types, product_ids, retailer_id, start_date, *args, **kwargs):  # noqa: E501
        """AuctionDisplayLineItemCreateModel - a model defined in OpenAPI

        Args:
            bidding (BiddingRequest):
            budget (float): The budget for the line item
            creative_ids ([str]): The list of creative ids associated with the line item.
            is_active (bool): Indicates whether the line item is active.
            media_type (str): The media type of the line item.
            name (str): The name of the line item.
            pacing (LineItemPacingRequest):
            page_types ([str]): The list of page types configured for the line item.
            product_ids ([str]): The list of product ids associated with the line item.
            retailer_id (str): The retailer id of the associated retailer.
            start_date (datetime): The start date of the line item.

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            end_date (datetime, none_type): The end date of the line item.. [optional]  # noqa: E501
            frequency_capping (LineItemCappingTargetRequest): [optional]  # noqa: E501
            targets (TargetsRequest): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.bidding = bidding
        self.budget = budget
        self.creative_ids = creative_ids
        self.is_active = is_active
        self.media_type = media_type
        self.name = name
        self.pacing = pacing
        self.page_types = page_types
        self.product_ids = product_ids
        self.retailer_id = retailer_id
        self.start_date = start_date
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, bidding, budget, creative_ids, is_active, media_type, name, pacing, page_types, product_ids, retailer_id, start_date, *args, **kwargs):  # noqa: E501
        """AuctionDisplayLineItemCreateModel - a model defined in OpenAPI

        Args:
            bidding (BiddingRequest):
            budget (float): The budget for the line item
            creative_ids ([str]): The list of creative ids associated with the line item.
            is_active (bool): Indicates whether the line item is active.
            media_type (str): The media type of the line item.
            name (str): The name of the line item.
            pacing (LineItemPacingRequest):
            page_types ([str]): The list of page types configured for the line item.
            product_ids ([str]): The list of product ids associated with the line item.
            retailer_id (str): The retailer id of the associated retailer.
            start_date (datetime): The start date of the line item.

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            end_date (datetime, none_type): The end date of the line item.. [optional]  # noqa: E501
            frequency_capping (LineItemCappingTargetRequest): [optional]  # noqa: E501
            targets (TargetsRequest): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.bidding = bidding
        self.budget = budget
        self.creative_ids = creative_ids
        self.is_active = is_active
        self.media_type = media_type
        self.name = name
        self.pacing = pacing
        self.page_types = page_types
        self.product_ids = product_ids
        self.retailer_id = retailer_id
        self.start_date = start_date
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
