# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from criteo_api_retailmedia_v2021_07.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from criteo_api_retailmedia_v2021_07.model.access_token_model import AccessTokenModel
from criteo_api_retailmedia_v2021_07.model.application_summary_model import ApplicationSummaryModel
from criteo_api_retailmedia_v2021_07.model.application_summary_model_resource import ApplicationSummaryModelResource
from criteo_api_retailmedia_v2021_07.model.application_summary_model_response import ApplicationSummaryModelResponse
from criteo_api_retailmedia_v2021_07.model.auction_line_item_create_model_request import AuctionLineItemCreateModelRequest
from criteo_api_retailmedia_v2021_07.model.auction_line_item_paged_list_response import AuctionLineItemPagedListResponse
from criteo_api_retailmedia_v2021_07.model.auction_line_item_response import AuctionLineItemResponse
from criteo_api_retailmedia_v2021_07.model.auction_line_item_update_model_request import AuctionLineItemUpdateModelRequest
from criteo_api_retailmedia_v2021_07.model.bad_request import BadRequest
from criteo_api_retailmedia_v2021_07.model.common_error import CommonError
from criteo_api_retailmedia_v2021_07.model.common_line_item_paged_list_response import CommonLineItemPagedListResponse
from criteo_api_retailmedia_v2021_07.model.common_line_item_response import CommonLineItemResponse
from criteo_api_retailmedia_v2021_07.model.common_problem import CommonProblem
from criteo_api_retailmedia_v2021_07.model.common_warning import CommonWarning
from criteo_api_retailmedia_v2021_07.model.envelope_report_request import EnvelopeReportRequest
from criteo_api_retailmedia_v2021_07.model.envelope_report_status import EnvelopeReportStatus
from criteo_api_retailmedia_v2021_07.model.error import Error
from criteo_api_retailmedia_v2021_07.model.external_account import ExternalAccount
from criteo_api_retailmedia_v2021_07.model.external_auction_line_item import ExternalAuctionLineItem
from criteo_api_retailmedia_v2021_07.model.external_auction_line_item_create_model import ExternalAuctionLineItemCreateModel
from criteo_api_retailmedia_v2021_07.model.external_auction_line_item_update_model import ExternalAuctionLineItemUpdateModel
from criteo_api_retailmedia_v2021_07.model.external_balance import ExternalBalance
from criteo_api_retailmedia_v2021_07.model.external_balance_campaign import ExternalBalanceCampaign
from criteo_api_retailmedia_v2021_07.model.external_brand import ExternalBrand
from criteo_api_retailmedia_v2021_07.model.external_campaign import ExternalCampaign
from criteo_api_retailmedia_v2021_07.model.external_campaign_attributes import ExternalCampaignAttributes
from criteo_api_retailmedia_v2021_07.model.external_catalog_request import ExternalCatalogRequest
from criteo_api_retailmedia_v2021_07.model.external_catalog_status import ExternalCatalogStatus
from criteo_api_retailmedia_v2021_07.model.external_common_line_item import ExternalCommonLineItem
from criteo_api_retailmedia_v2021_07.model.external_delete_balance_campaign import ExternalDeleteBalanceCampaign
from criteo_api_retailmedia_v2021_07.model.external_editable_campaign_attributes import ExternalEditableCampaignAttributes
from criteo_api_retailmedia_v2021_07.model.external_keyword_target import ExternalKeywordTarget
from criteo_api_retailmedia_v2021_07.model.external_line_item_capping import ExternalLineItemCapping
from criteo_api_retailmedia_v2021_07.model.external_post_campaign import ExternalPostCampaign
from criteo_api_retailmedia_v2021_07.model.external_preferred_line_item import ExternalPreferredLineItem
from criteo_api_retailmedia_v2021_07.model.external_preferred_line_item_create_model import ExternalPreferredLineItemCreateModel
from criteo_api_retailmedia_v2021_07.model.external_preferred_line_item_update_model import ExternalPreferredLineItemUpdateModel
from criteo_api_retailmedia_v2021_07.model.external_promoted_product import ExternalPromotedProduct
from criteo_api_retailmedia_v2021_07.model.external_put_balance_campaign import ExternalPutBalanceCampaign
from criteo_api_retailmedia_v2021_07.model.external_put_campaign import ExternalPutCampaign
from criteo_api_retailmedia_v2021_07.model.external_retailer import ExternalRetailer
from criteo_api_retailmedia_v2021_07.model.input_resource_of_auction_line_item_create_model import InputResourceOfAuctionLineItemCreateModel
from criteo_api_retailmedia_v2021_07.model.input_resource_of_preferred_line_item_create_model import InputResourceOfPreferredLineItemCreateModel
from criteo_api_retailmedia_v2021_07.model.json_api_body_with_external_id_of_editable_campaign_attributes_and_campaign import JsonApiBodyWithExternalIdOfEditableCampaignAttributesAndCampaign
from criteo_api_retailmedia_v2021_07.model.json_api_body_with_id_of_int64_and_account_and_account import JsonApiBodyWithIdOfInt64AndAccountAndAccount
from criteo_api_retailmedia_v2021_07.model.json_api_body_with_id_of_int64_and_balance_and_balance import JsonApiBodyWithIdOfInt64AndBalanceAndBalance
from criteo_api_retailmedia_v2021_07.model.json_api_body_with_id_of_int64_and_brand_and_brand import JsonApiBodyWithIdOfInt64AndBrandAndBrand
from criteo_api_retailmedia_v2021_07.model.json_api_body_with_id_of_int64_and_campaign_and_campaign import JsonApiBodyWithIdOfInt64AndCampaignAndCampaign
from criteo_api_retailmedia_v2021_07.model.json_api_body_with_id_of_int64_and_catalog_status_and_catalog_status import JsonApiBodyWithIdOfInt64AndCatalogStatusAndCatalogStatus
from criteo_api_retailmedia_v2021_07.model.json_api_body_with_id_of_int64_and_retailer_and_retailer import JsonApiBodyWithIdOfInt64AndRetailerAndRetailer
from criteo_api_retailmedia_v2021_07.model.json_api_body_with_id_of_string_and_promoted_product_and_promoted_product import JsonApiBodyWithIdOfStringAndPromotedProductAndPromotedProduct
from criteo_api_retailmedia_v2021_07.model.json_api_body_without_id_of_campaign_attributes_and_campaign import JsonApiBodyWithoutIdOfCampaignAttributesAndCampaign
from criteo_api_retailmedia_v2021_07.model.json_api_body_without_id_of_catalog_request_and_catalog_request import JsonApiBodyWithoutIdOfCatalogRequestAndCatalogRequest
from criteo_api_retailmedia_v2021_07.model.json_api_data_request_of_delete_balance_campaign import JsonApiDataRequestOfDeleteBalanceCampaign
from criteo_api_retailmedia_v2021_07.model.json_api_data_request_of_put_balance_campaign import JsonApiDataRequestOfPutBalanceCampaign
from criteo_api_retailmedia_v2021_07.model.json_api_data_request_with_id_of_string_and_promoted_product import JsonApiDataRequestWithIdOfStringAndPromotedProduct
from criteo_api_retailmedia_v2021_07.model.json_api_page_response_of_account import JsonApiPageResponseOfAccount
from criteo_api_retailmedia_v2021_07.model.json_api_page_response_of_balance import JsonApiPageResponseOfBalance
from criteo_api_retailmedia_v2021_07.model.json_api_page_response_of_brand import JsonApiPageResponseOfBrand
from criteo_api_retailmedia_v2021_07.model.json_api_page_response_of_campaign import JsonApiPageResponseOfCampaign
from criteo_api_retailmedia_v2021_07.model.json_api_page_response_of_retailer import JsonApiPageResponseOfRetailer
from criteo_api_retailmedia_v2021_07.model.json_api_page_response_of_string_and_promoted_product import JsonApiPageResponseOfStringAndPromotedProduct
from criteo_api_retailmedia_v2021_07.model.json_api_request_of_catalog_request import JsonApiRequestOfCatalogRequest
from criteo_api_retailmedia_v2021_07.model.json_api_single_response_of_campaign import JsonApiSingleResponseOfCampaign
from criteo_api_retailmedia_v2021_07.model.json_api_single_response_of_catalog_status import JsonApiSingleResponseOfCatalogStatus
from criteo_api_retailmedia_v2021_07.model.keyword_target_request import KeywordTargetRequest
from criteo_api_retailmedia_v2021_07.model.keyword_target_response import KeywordTargetResponse
from criteo_api_retailmedia_v2021_07.model.map_string import MapString
from criteo_api_retailmedia_v2021_07.model.o_auth_error_model import OAuthErrorModel
from criteo_api_retailmedia_v2021_07.model.page_metadata import PageMetadata
from criteo_api_retailmedia_v2021_07.model.page_of_balance_campaign import PageOfBalanceCampaign
from criteo_api_retailmedia_v2021_07.model.preferred_line_item_create_model_request import PreferredLineItemCreateModelRequest
from criteo_api_retailmedia_v2021_07.model.preferred_line_item_paged_list_response import PreferredLineItemPagedListResponse
from criteo_api_retailmedia_v2021_07.model.preferred_line_item_response import PreferredLineItemResponse
from criteo_api_retailmedia_v2021_07.model.preferred_line_item_update_model_request import PreferredLineItemUpdateModelRequest
from criteo_api_retailmedia_v2021_07.model.problem_details import ProblemDetails
from criteo_api_retailmedia_v2021_07.model.report_request import ReportRequest
from criteo_api_retailmedia_v2021_07.model.report_request_attributes import ReportRequestAttributes
from criteo_api_retailmedia_v2021_07.model.report_status import ReportStatus
from criteo_api_retailmedia_v2021_07.model.report_status_attributes import ReportStatusAttributes
from criteo_api_retailmedia_v2021_07.model.resource_of_auction_line_item import ResourceOfAuctionLineItem
from criteo_api_retailmedia_v2021_07.model.resource_of_auction_line_item_update_model import ResourceOfAuctionLineItemUpdateModel
from criteo_api_retailmedia_v2021_07.model.resource_of_common_line_item import ResourceOfCommonLineItem
from criteo_api_retailmedia_v2021_07.model.resource_of_keyword_target import ResourceOfKeywordTarget
from criteo_api_retailmedia_v2021_07.model.resource_of_preferred_line_item import ResourceOfPreferredLineItem
from criteo_api_retailmedia_v2021_07.model.resource_of_preferred_line_item_update_model import ResourceOfPreferredLineItemUpdateModel
