"""
    Criteo API

    Criteo API - MarketingSolutions  # noqa: E501

    The version of the OpenAPI document: Preview
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from criteo_api_marketingsolutions_preview.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from criteo_api_marketingsolutions_preview.exceptions import ApiAttributeError


def lazy_import():
    from criteo_api_marketingsolutions_preview.model.product_set_rule import ProductSetRule
    globals()['ProductSetRule'] = ProductSetRule


class ProductSet(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('client_type',): {
            'UNKNOWN': "Unknown",
            'CGROWTH': "CGrowth",
            'CMAX': "CMax",
        },
        ('status',): {
            'UNKNOWN': "Unknown",
            'DRAFT': "Draft",
            'PENDING': "Pending",
            'VALID': "Valid",
            'INVALID': "Invalid",
            'DELETED': "Deleted",
        },
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = True

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'client_type': (str,),  # noqa: E501
            'creation_date': (str,),  # noqa: E501
            'dataset_id': (str,),  # noqa: E501
            'keep_variant_products': (bool,),  # noqa: E501
            'minimum_number_of_products': (int,),  # noqa: E501
            'name': (str,),  # noqa: E501
            'number_of_products': (int, none_type,),  # noqa: E501
            'rules': ([ProductSetRule],),  # noqa: E501
            'status': (str,),  # noqa: E501
            'id': (str, none_type,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'client_type': 'clientType',  # noqa: E501
        'creation_date': 'creationDate',  # noqa: E501
        'dataset_id': 'datasetId',  # noqa: E501
        'keep_variant_products': 'keepVariantProducts',  # noqa: E501
        'minimum_number_of_products': 'minimumNumberOfProducts',  # noqa: E501
        'name': 'name',  # noqa: E501
        'number_of_products': 'numberOfProducts',  # noqa: E501
        'rules': 'rules',  # noqa: E501
        'status': 'status',  # noqa: E501
        'id': 'id',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, client_type, creation_date, dataset_id, keep_variant_products, minimum_number_of_products, name, number_of_products, rules, status, *args, **kwargs):  # noqa: E501
        """ProductSet - a model defined in OpenAPI

        Args:
            client_type (str): The client type of the product set
            creation_date (str): The creation date of the product set (UTC time in ISO8601 format). Example: \"02/25/2022 14:51:26\".  Can be null if the value isn't available.
            dataset_id (str): The dataset to which the product set belong
            keep_variant_products (bool):
            minimum_number_of_products (int): Minimum amount of products that should match the product set to consider it valid.  Greater or equal than one.
            name (str): The name of the product set
            number_of_products (int, none_type): The number of product matching the product set.  Can be null for newly created product set.
            rules ([ProductSetRule]): The rules identifying the product belonging to the set
            status (str): The status of the product set

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (str, none_type): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.client_type = client_type
        self.creation_date = creation_date
        self.dataset_id = dataset_id
        self.keep_variant_products = keep_variant_products
        self.minimum_number_of_products = minimum_number_of_products
        self.name = name
        self.number_of_products = number_of_products
        self.rules = rules
        self.status = status
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, client_type, creation_date, dataset_id, keep_variant_products, minimum_number_of_products, name, number_of_products, rules, status, *args, **kwargs):  # noqa: E501
        """ProductSet - a model defined in OpenAPI

        Args:
            client_type (str): The client type of the product set
            creation_date (str): The creation date of the product set (UTC time in ISO8601 format). Example: \"02/25/2022 14:51:26\".  Can be null if the value isn't available.
            dataset_id (str): The dataset to which the product set belong
            keep_variant_products (bool):
            minimum_number_of_products (int): Minimum amount of products that should match the product set to consider it valid.  Greater or equal than one.
            name (str): The name of the product set
            number_of_products (int, none_type): The number of product matching the product set.  Can be null for newly created product set.
            rules ([ProductSetRule]): The rules identifying the product belonging to the set
            status (str): The status of the product set

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (str, none_type): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.client_type = client_type
        self.creation_date = creation_date
        self.dataset_id = dataset_id
        self.keep_variant_products = keep_variant_products
        self.minimum_number_of_products = minimum_number_of_products
        self.name = name
        self.number_of_products = number_of_products
        self.rules = rules
        self.status = status
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
