"""
    Criteo API

    Criteo API - MarketingSolutions  # noqa: E501

    The version of the OpenAPI document: 2024-10
    Generated by: https://openapi-generator.tech
"""


__version__ = "2024.10.0.250709"

# import ApiClient
from criteo_api_marketingsolutions_v2024_10.api_client import ApiClient
from criteo_api_marketingsolutions_v2024_10.criteo_api_client import CriteoApiClient
from criteo_api_marketingsolutions_v2024_10.api_client_builder import ApiClientBuilder
from criteo_api_marketingsolutions_v2024_10 import flow_constants

# import Configuration
from criteo_api_marketingsolutions_v2024_10.configuration import Configuration

# import exceptions
from criteo_api_marketingsolutions_v2024_10.exceptions import OpenApiException
from criteo_api_marketingsolutions_v2024_10.exceptions import ApiAttributeError
from criteo_api_marketingsolutions_v2024_10.exceptions import ApiTypeError
from criteo_api_marketingsolutions_v2024_10.exceptions import ApiValueError
from criteo_api_marketingsolutions_v2024_10.exceptions import ApiKeyError
from criteo_api_marketingsolutions_v2024_10.exceptions import ApiException



