# flake8: noqa

"""
    Criteo API

    Criteo publicly exposed API  # noqa: E501

    The version of the OpenAPI document: 2021-07
    Generated by: https://openapi-generator.tech
"""


__version__ = "2021.07.0.220926"

# import ApiClient
from criteo_api_marketingsolutions_v2021_07.api_client import ApiClient

# import Configuration
from criteo_api_marketingsolutions_v2021_07.configuration import Configuration

# import exceptions
from criteo_api_marketingsolutions_v2021_07.exceptions import OpenApiException
from criteo_api_marketingsolutions_v2021_07.exceptions import ApiAttributeError
from criteo_api_marketingsolutions_v2021_07.exceptions import ApiTypeError
from criteo_api_marketingsolutions_v2021_07.exceptions import ApiValueError
from criteo_api_marketingsolutions_v2021_07.exceptions import ApiKeyError
from criteo_api_marketingsolutions_v2021_07.exceptions import ApiException
